[package]
name = "feature_level_report"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.5.46"
regex = "1.11.2"
flate2 = "1.1.2"
